$schema: https://azuremlschemas.azureedge.net/latest/environment.schema.json
name: env-battery-cv
version: 1
build:
  path: .
  dockerfile_path: Dockerfile
description: "Anomalib 2.2.0, YOLO, adlfs, fsspec 등이 포함된 배터리 이상탐지 전용 환경"
